#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_voxels = env_modules.Clone()

# Shader headers
env_voxels.GLSL_HEADER("compute_raymarch.glsl")
env_voxels.GLSL_HEADER("compute_sim.glsl")
env_voxels.GLSL_HEADER("compute_light.glsl")
env_voxels.GLSL_HEADER("compute_occupancy.glsl")
env_voxels.GLSL_HEADER("compute_active_list.glsl")
env_voxels.GLSL_HEADER("compute_active_dispatch.glsl")
env_voxels.Depends(Glob("*.glsl.gen.h"), ["#glsl_builders.py"])

module_obj = []

env_voxels.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
